# Generated by Django 5.0.3 on 2024-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
