# Generated by Django 5.0.3 on 2024-03-19 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amenities', models.CharField(max_length=300)),
                ('bedrooms', models.SmallIntegerField(blank=True)),
                ('sittingRooms', models.SmallIntegerField(blank=True)),
                ('internalToilets', models.SmallIntegerField(blank=True)),
                ('internalKitchens', models.SmallIntegerField(blank=True)),
                ('width', models.SmallIntegerField(blank=True)),
                ('length', models.SmallIntegerField(blank=True)),
                ('price', models.IntegerField()),
                ('caution', models.IntegerField(blank=True, default=0)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.address')),
                ('catergory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.catergory')),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
