# Generated by Django 5.0.3 on 2024-03-19 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0003_alter_property_bedrooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='interestedUsers',
            field=models.ManyToManyField(blank=True, related_name='interestedUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
