# Generated by Django 5.0.3 on 2024-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0004_alter_property_interestedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
