# Generated by Django 5.0.3 on 2024-03-21 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0006_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bedrooms',
            new_name='bed_rooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='interestedUsers',
            new_name='interested_users',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='internalKitchens',
            new_name='internal_kitchens',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='internalToilets',
            new_name='internal_toilets',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='postedBy',
            new_name='posted_by',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='sittingRooms',
            new_name='sitting_rooms',
        ),
        migrations.AddField(
            model_name='property',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2024, 3, 21)),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='Properties.amenity'),
        ),
    ]
