# Generated by Django 5.0.3 on 2024-03-22 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0007_amenity_rename_bedrooms_property_bed_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(default='mile 3', max_length=40),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.country')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.province')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Properties.location'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
