# Generated by Django 5.0.3 on 2024-03-22 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0009_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Properties.area'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Properties.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Properties.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='province',
            field=models.ForeignKey(default=1 , on_delete=django.db.models.deletion.CASCADE, to='Properties.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Properties.country'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
