# Generated by Django 5.0.3 on 2024-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0010_alter_property_location_area_city_city_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bed_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='internal_kitchens',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='internal_toilets',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='length',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sitting_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
