# Generated by Django 5.0.3 on 2024-03-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0011_alter_property_bed_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
