# Generated by Django 5.0.3 on 2024-03-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0013_rename_catergory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
