# Generated by Django 5.0.3 on 2024-03-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0014_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='property'),
        ),
    ]
