# Generated by Django 5.0.3 on 2024-04-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0015_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
