# Generated by Django 5.0.3 on 2024-04-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.FileField(default='no-image.png', upload_to='chats'),
            preserve_default=False,
        ),
    ]
